App\Entity\OAuthRefreshToken:
    type: entity
    table: oauth_refresh_tokens
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    manyToOne:
        client:
            targetEntity: App\Entity\OAuthClient
            joinColumns:
                client_id:
                    referencedColumnName: id
        user:
            targetEntity: App\Entity\Usuario
            joinColumns:
                user_id:
                    referencedColumnName: id
